name: Build & Push

on:
  workflow_dispatch:
  push:
    branches:
      - test

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Login en Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u calonsocaminafpfomento --password-stdin

      - name: Construir imagen
        run: docker build -t calonsocaminafpfomento/daw-web:latest .

      - name: Subir imagen a Docker Hub
        run: docker push calonsocaminafpfomento/daw-web:latest

      - name: Ejecutar contenedor en puerto 8888
        run: |
          docker stop daw-web-container || true
          docker rm daw-web-container || true
          docker run -d -p 8888:80 --name daw-web-container calonsocaminafpfomento/daw-web:latest
